sudo: required
services:
  - docker

install:
  - docker build -t centos-build .

script:
  - docker run -v "$(pwd):/target" -it centos-build /target/nginx-module-vts.spec 1.16.1 /target/repo/stable
  - docker run -v "$(pwd):/target" -it centos-build /target/nginx-module-vts.spec 1.17.8 /target/repo/mainline

before_deploy:
  - mkdir -p gh-pages && curl -L https://github.com/corux/corux.github.io/archive/master.tar.gz | tar xz --strip 1 --directory gh-pages
  - mkdir -p gh-pages/nginx-modules/centos/7 && cp -a repo/stable/* gh-pages/nginx-modules/centos/7/
  - mkdir -p gh-pages/nginx-modules/mainline/centos/7 && cp -a repo/mainline/* gh-pages/nginx-modules/mainline/centos/7/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: gh-pages
  repo: corux/corux.github.io
  target-branch: master
  on:
    branch: master
